services:
  - type: web
    name: stockpredict-live
    runtime: node
    plan: free
    autoDeploy: true
    healthCheckPath: /api/health
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: FINNHUB_API_KEY
        sync: false
      - key: PORT
        value: 8787
